import re
import logging

logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = "\n\n*Disclaimer: This is an automated analysis generated by an AI startup simulator. It does not constitute professional financial or legal advice.*"

def apply_disclaimer(plan_markdown: str) -> str:
    """
    Checks if Financial Projection and Key Risks sections contain a disclaimer.
    If not, appends the disclaimer text to those sections.
    """
    
    sections_to_check = [
        "Financial Projection",
        "Key Risks"
    ]
    
    for section_name in sections_to_check:
        # Regex to find the section header and everything up to the next header or EOF
        # The section header could be any level, e.g., ## Financial Projection or ### 5. Financial Projection
        pattern = re.compile(rf"(^#+\s*(?:\d+\.\s*)?{section_name}.*?)(?=^#+|\Z)", re.MULTILINE | re.DOTALL | re.IGNORECASE)
        match = pattern.search(plan_markdown)
        
        if match:
            section_content = match.group(1)
            # Check if disclaimer is present
            if "disclaimer" not in section_content.lower() and "automated analysis" not in section_content.lower():
                logger.info(f"Applying missing disclaimer to '{section_name}' section.")
                new_section_content = section_content.rstrip() + DISCLAIMER_TEXT + "\n\n"
                plan_markdown = plan_markdown[:match.start()] + new_section_content + plan_markdown[match.end():]
                
    return plan_markdown
